# This demonstration of triton-nginx has port mappings so we can test it
# on docker-machine locally.

nginx:
    extends:
      file: common-compose.yml
      service: nginx
    build: ..
    links:
    - consul:consul
    ports:
    - 8080:80

app:
    extends:
      file: common-compose.yml
      service: app
    links:
    - consul:consul
    ports:
    - 8000:8000

consul:
    extends:
      file: common-compose.yml
      service: consul
    ports:
    - 8500:8500
